sudo: required
language: bash
env:
  global:
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASS
    - secure: 2l2dhMyLPSYsqZ4Um5tJn4U2Dk81nk6X4Ma2JiqiBL/LV7thMm8N5k09hGJ7LHH7HBI2fK1QZmgAi/1e/NwtKiZB2FyH8FdICusViXs6kKjX/ZOzbCVNwuFh39Gv5rIZ4NQDRxnpTL3Uf6uh099W2bHkrs4i64TmfCE7CKsd+cUu/oSy83krd6qzgNbKypQJo5pAhjN+tUHzlb5qxeyN2jipiKY/spH+DamOd5DhoIIZFMjPXVWmOLhCxH1xe3DvViA+i/obvP4Mo3durwmFP8ZNHUSp1yW5XVBNm+uCtuNBRsNbOBjfc2sxGm0sYNH7OZOqkv/nAUDFluqvzpc5/d0C0nmeJvdSC51oCw7H9dfvcD4gOJkbXYEXFAP4NuVz84Rpph7fyesmzhtlIaokdHNQRxoUno1FvkueQMUDWbxknxgi7yxH0GDRDte73UzrnfyM+qH/XhP72hcB6QjcEPDlu/aE+6I5xsSu5IV8PbJOI/YL3nUcfthmEN8iyg2LmL++W7drDrHOR2ZLJVwxdR8Y6yesPBGbEpzlkjjVsa2pnmyZLTPhsmvC1boQoY5AusjfpMCEv385cag9STSmkfNEq/AJ2MEZWT1EblGrhetrOEcWB76qY+GWehzg20y4UG5NtMinY8WCiY8j3ffr1Xih6i23Y1hBcQWHWfkmuOA=
# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass
before_install:
  # Download Git Large File Storage extension as the Greenplum installer found in the Github repo is stored there
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs=1.4.4

  # And now populate the large files into the repo
  - git lfs pull
script:
  - ./build.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
    tags: false
notifications:
  email:
    on_success: never
    on_failure: never
