sudo: required

language: bash

env:
  global:
      - DEPLOY_HOST=rpm.palette-software.com
      - DEPLOY_PATH=/var/palette-rpm-repo
      - DEPLOY_USER=palette-rpm

      # travis encrypt DEPLOY_PASSWORD=...
      - secure: "JzBjDiJ3tchdYq7A0Rs+7OU44tq49X42sKgu6mYQHYEUXpLi1aVA4mzmHih96FRrgiR/FwI2dxstCEl7Y759KV3z9Hqr+tIlKDihCkTcK45XLhrLa7X3QMbgN5hY10rP0QF7MffwMLjT6SgPCVTzJ6u9PXiHjN7XQpwRReiLCS10q3C1VuYzss4Xu1D9nEJZuRqstcrwV9zRYiXuqSc7RECezpAKtr3UBFIw4g03UQq2LTqr3ip8OvxWyXjxbabRc0wNglJEBpCJaPy4yIgp+brrFfdQDcHH80pH2paMcFiZwUuUATCzl5SyMh9oA41p2n2dkYVSM6k7VlPK3Sbh7bXjkNh+8bHQap1zMTbB6TryNqIwyMe9Q9vXudyMm6y94PlEEEawsFL/CJrgyOw3WPdwM5TWcn8kL8bL6nj664568neoRyFptPzO8FTcFK1UL17SA6engyWrQ2Om51NMk/2D3O8y8DPeX9YZe5idZBlnvFCCORXrzOlxaz7k4Kbr4GYF1gyfOeN9L1FxGZEolTQloeM/sU80eiaEfjKFq9O0fXhtjsOg6D8Gly7cI8V96MDDS5ZSMV4ficKH0fCkHrvuHOiWG6pogV2edGg+IBQdPE3/l1coZ4wTkJQWEGLEv403a1W7IeG0AhjxUz6K9JDvXZz5V9MLksRGBxN7S4Q="
      # travis encrypt GITHUB_TOKEN=...
      - secure: "E/JDvHMS93Er1MA6KGvzvaZnDBrAUW8gW3K9WmW3vfvFoe960bcNIpo5IUPAgFGMk04p8ORQl9BGLu/cPG+Rr1CAQ1fasGNIhe6IILbQ9NM9KFYyeW8ipEONLnVRxJ/2T4S86EWg+/c2xpUFJc+8qm+lwPXSBK8hMXecMUs6Vhk3qEsn7L/QGeBDhbjOD8r3vdxg+JmChaEYtN60svBP6Ul1X43ezlvLzPrcN5Uht6QwT2mLkd7ivrRRPBqrhQ5dKb3FX2LttiO3pGmSD7sEpuIR0OxGqFMq2ZVyZRSuZOSk6VPnYbSNlQS/2aUEdszdcUehXlwOwH0lUn61E7zCsxd/7XCHKdAeqiHzPRKlr7cwZPQJ1mGOcrcQZGOFoFb3e1w+pgZhAXvUmgD6ANttlS5Q2Z1ujs5oBc4BiG6HYjLzyB4C4UY03J2RNusJvFQUUwJP0/PH0BBFxReogTV18SZnMqKbSm6qjr+otKGmGtVYfRAclHCEzucQRVC09hyfRx29XwX0Qclb5oDZrLReZq0N4LPp1ByQbeUHprw6CPdB0xXDHScpYeFjOTfJlI2V6OQe1fF9mL/xJrlO7PFHSMNOY4XIjMY2+yAVRA86No4D5mFlTV/lTvboJ27vVFmVyDVCKi/iBVntVF6GGbACpQBv1YIzhT5SOkDeFso+cdM="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

script:
  - ./build.sh . 4.3.7.3

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
    tags: false

notifications:
  email:
    on_success: never
    on_failure: never
